### ISSUE TITLE
When a Mythic+ dungeon is completed, the plugin does not automatically pop up the interface

### ISSUE THREAD

**Issue by moshouchajian** [Kirri777/DoYouNeedThat#8]
When a Mythic+ dungeon is completed, the plugin does not automatically pop up the interface

**Comment by Kirri777** [comment]
Apologies for the confusion. I don’t run mythic+ dungeons, so I wasn’t aware that the items dropped there are tradable. By default, the module disabled the window showing in mythic+, but I can change that in the code. However, please note that the window will appear after every boss, not just the final one.

Can you change this line in Core.lua and check if this working?

From:

```lua
if self.Config.openAfterEncounter and difficulty ~= 8 then
    self.lootFrame:Show()
end
```

To:

```lua
if self.Config.openAfterEncounter then
    self.lootFrame:Show()
end
```

**Comment by Kirri777** [comment]
Can you check this version?
https://github.com/Kirri777/DoYouNeedThat/tree/Kirri777/issue8

Added function to check if you killed last boss on m+

**Comment by moshouchajian** [comment]
> Can you check this version? https://github.com/Kirri777/DoYouNeedThat/tree/Kirri777/issue8
> 
> Added function to check if you killed last boss on m+

I tried it, but the plugin still doesn’t automatically pop up after the Mythic+ dungeon ends.

**Comment by Kirri777** [comment]
Ok next update to check on https://github.com/Kirri777/DoYouNeedThat/tree/Kirri777/issue8

Have you selected this option?

![image](https://github.com/user-attachments/assets/a4c9b39b-402d-4f45-aa41-785013c54564)

Are the Mythic+ dungeons you tested on this list?

```lua
--[[
	List of all mythic+ last boss IDs (encounterIDs)

	@see https://wago.tools/db2/DungeonEncounter
	@see https://wowpedia.fandom.com/wiki/DungeonEncounterID
--]]
Utils.MythicPlusLastBosses = {
	'1049', -- Erudax (Grim Batol 4.x)
	'2883', -- Void Speaker Eirich (The Stonevault)
	'2839', -- Rasha'nan (The Dawnbreaker)
	'2909', -- Izo, the Grand Splicer (City of Threads)
	'2901', -- Ki'katal the Harvester (Ara-Kara, City of Echoes)
	'2393', -- Tred'ova (Mists of Tirna Scithe)
	'2390', -- Nalthor the Rimebinder (The Necrotic Wake)
	'2100', -- Viq'Goth <Terror of the Deep> (Siege of Boralus)
	'2848', -- Prioress Murrpray (Priory of the Sacred Flame)
}
```

If both yes, can you run debug and check what its return on the last boss?

Need only these info:

![image](https://github.com/user-attachments/assets/b19f20e4-6891-4baf-b0a0-147e434ba44e)

**Comment by moshouchajian** [comment]
Thanks! I tried it, and now the addon is working fine. If I encounter any other issues, I’ll leave a message.
